### ISSUE TITLE
Save Option

### ISSUE THREAD

**Issue by KiraYamatoSD** [GetRektByMe/NovelAPI#5]
I was wondering if it is possible to include a save function that will save the parsed information to TXT or HTML format under the name of the novel from the URL?

**Comment by byronvanstien** [comment]
Considering it returns as a dictionary it'd be as simple as writing the term + '.txt' or '.html' as the filename and then writing the entries you want from the dictionaries to the txt/html file. Yes it's possible.

**Comment by ccubed** [comment]
``` python
import json
with open('ouput', 'w') as file:
    json.dump(data, file, indent=2)
```
